### ISSUE TITLE
question about forward_free() function

### ISSUE THREAD

**Issue by zhFuECL** [jzbontar/mc-cnn#13]
As torch has its own forward function, why use forward_free in net_te1?

**Comment by jzbontar** [comment]
forward_free is a memory optimized version of torch's default forward method. The idea is simple: if you don't need to compute gradients, you don't need to store the outputs of each layer.

Today, I would simply use https://github.com/fmassa/optimize-net, but this module did not exist when the mc-cnn code was written.

**Comment by zhFuECL** [comment]
@jzbontar  I found that in evaluation mode, forward_free() perform much better than optnet(set parameters to  {mode='inference', inplace=false} )
