### ISSUE TITLE
StereoJoin_forward2() missing

### ISSUE THREAD

**Issue by chaneyw** [jzbontar/mc-cnn#14]
Hi Jure,

I was wondering about the fast Middlebury trained network, it seems to use nn.StereoJoin layer which calls adcensus.StereoJoin_forward2() in the forward pass, but there doesn't seem to be a definition for that function in the .cu file.

**Comment by jzbontar** [comment]
Hi,

I think adcensus.StereoJoin_forward2() is not neccesary anymore. I tried running the code today and it works on my machine. Just make sure you match the second argument to the main.lua script (fast or slow) with the network you are loading. In particular, if you try to run

./main.lua kitti **slow** -a predict -net_fname net/net_kitti_**fast**_-a_train_all.t7 -left samples/input/kittiL.png -right samples/input/kittiR.png -disp_max 70

it fails by complaining that `StereoJoin_forward2` is not found. But this works:

./main.lua kitti **fast** -a predict -net_fname net/net_kitti_**fast**_-a_train_all.t7 -left samples/input/kittiL.png -right samples/input/kittiR.png -disp_max 70

Let me know if it works for you.

**Comment by chaneyw** [comment]
Hi Jure,

Thanks, sorry, I guess I didn't have enough copy. I was stripping the code down to simplify it and was simply running the forward_free fx on the loaded net without looking at main and realizing that it chops off the top layer and replaces it. Everything is working smoothly.
