### ISSUE TITLE
luajit: c++ exception

### ISSUE THREAD

**Issue by Jessie2014** [jzbontar/mc-cnn#15]
while i'm running this command :./preprocess_kitti.lua, it outputs:
dataset 2012
1
luajit: c++ exception
what's wrong with it?

**Comment by jzbontar** [comment]
I tried running this script today with the newest version of torch and it works on my system. Let's try the following:

1. Make sure the images are in the correct location. Run the following command from the mc-cnn directory:

    $ identify data.kitti/unzip/training/image_0/000000_10.png
    data.kitti/unzip/training/image_0/000000_10.png PNG 1226x370 1226x370+0+0 8-bit sRGB 256c 258KB 0.000u 0:00.000

2. Can you try and figure out which line causes the c++ exception. The easiest way is to add print statements in the preprocess_kitti.lua script.

**Comment by Jessie2014** [comment]
Thanks a lot for your kindly reply, yes, there is some wrong with my data folder.
