### ISSUE TITLE
Setup query regarding Png++ install (unrelated to this repository)

### ISSUE THREAD

**Issue by ShreyasSkandan** [jzbontar/mc-cnn#17]
I'm trying to install Png++ with no sucess. I followed the instructions and tried to 'make' the installation.

This is my output from the first make command:

> shreyas@shreyas:~/png++-0.2.9$ make
> make -C example 
> make[1]: Entering directory `/home/shreyas/png++-0.2.9/example'
> Makefile:45: pixel_generator.dep: No such file or directory
> g++ -M  -Wall -I.. -I/usr/local/include -I/home/shreyas/anaconda2/include/libpng16  -g pixel_generator.cpp -o- | \
> 	  sed 's/\(pixel_generator\)\.o[ :]*/\1.o pixel_generator.dep : /g' > pixel_generator.dep
> make[1]: Leaving directory `/home/shreyas/png++-0.2.9/example'
> make[1]: Entering directory `/home/shreyas/png++-0.2.9/example'
> g++ -c -o pixel_generator.o pixel_generator.cpp -Wall -I.. -I/usr/local/include -I/home/shreyas/anaconda2/include/libpng16  -g
> g++ -o pixel_generator pixel_generator.o -L/usr/local/lib -L/home/shreyas/anaconda2/lib -lpng16  -g
> make[1]: Leaving directory `/home/shreyas/png++-0.2.9/example'

And when I try to run make test, this is my ouput:

> shreyas@shreyas:~/png++-0.2.9$ make test
> make test -C test 
> make[1]: Entering directory `/home/shreyas/png++-0.2.9/test'
> Makefile:64: convert_color_space.dep: No such file or directory
> Makefile:64: generate_gray_packed.dep: No such file or directory
> Makefile:64: read_write_gray_packed.dep: No such file or directory
> Makefile:64: generate_palette.dep: No such file or directory
> Makefile:64: write_gray_16.dep: No such file or directory
> Makefile:64: read_write_param.dep: No such file or directory
> Makefile:64: dump.dep: No such file or directory
> g++ -M  -Wall -I.. -I/usr/local/include -I/home/shreyas/anaconda2/include/libpng16  -g dump.cpp -o- | \
> 	  sed 's/\(dump\)\.o[ :]*/\1.o dump.dep : /g' > dump.dep
> g++ -M  -Wall -I.. -I/usr/local/include -I/home/shreyas/anaconda2/include/libpng16  -g read_write_param.cpp -o- | \
> 	  sed 's/\(read_write_param\)\.o[ :]*/\1.o read_write_param.dep : /g' > read_write_param.dep
> g++ -M  -Wall -I.. -I/usr/local/include -I/home/shreyas/anaconda2/include/libpng16  -g write_gray_16.cpp -o- | \
> 	  sed 's/\(write_gray_16\)\.o[ :]*/\1.o write_gray_16.dep : /g' > write_gray_16.dep
> g++ -M  -Wall -I.. -I/usr/local/include -I/home/shreyas/anaconda2/include/libpng16  -g generate_palette.cpp -o- | \
> 	  sed 's/\(generate_palette\)\.o[ :]*/\1.o generate_palette.dep : /g' > generate_palette.dep
> g++ -M  -Wall -I.. -I/usr/local/include -I/home/shreyas/anaconda2/include/libpng16  -g read_write_gray_packed.cpp -o- | \
> 	  sed 's/\(read_write_gray_packed\)\.o[ :]*/\1.o read_write_gray_packed.dep : /g' > read_write_gray_packed.dep
> g++ -M  -Wall -I.. -I/usr/local/include -I/home/shreyas/anaconda2/include/libpng16  -g generate_gray_packed.cpp -o- | \
> 	  sed 's/\(generate_gray_packed\)\.o[ :]*/\1.o generate_gray_packed.dep : /g' > generate_gray_packed.dep
> g++ -M  -Wall -I.. -I/usr/local/include -I/home/shreyas/anaconda2/include/libpng16  -g convert_color_space.cpp -o- | \
> 	  sed 's/\(convert_color_space\)\.o[ :]*/\1.o convert_color_space.dep : /g' > convert_color_space.dep
> make[1]: Leaving directory `/home/shreyas/png++-0.2.9/test'
> make[1]: Entering directory `/home/shreyas/png++-0.2.9/test'
> g++ -c -o convert_color_space.o convert_color_space.cpp -Wall -I.. -I/usr/local/include -I/home/shreyas/anaconda2/include/libpng16  -g
> g++ -o convert_color_space convert_color_space.o -L/usr/local/lib -L/home/shreyas/anaconda2/lib -lpng16  -g
> g++ -c -o generate_gray_packed.o generate_gray_packed.cpp -Wall -I.. -I/usr/local/include -I/home/shreyas/anaconda2/include/libpng16  -g
> g++ -o generate_gray_packed generate_gray_packed.o -L/usr/local/lib -L/home/shreyas/anaconda2/lib -lpng16  -g
> g++ -c -o read_write_gray_packed.o read_write_gray_packed.cpp -Wall -I.. -I/usr/local/include -I/home/shreyas/anaconda2/include/libpng16  -g
> g++ -o read_write_gray_packed read_write_gray_packed.o -L/usr/local/lib -L/home/shreyas/anaconda2/lib -lpng16  -g
> g++ -c -o generate_palette.o generate_palette.cpp -Wall -I.. -I/usr/local/include -I/home/shreyas/anaconda2/include/libpng16  -g
> g++ -o generate_palette generate_palette.o -L/usr/local/lib -L/home/shreyas/anaconda2/lib -lpng16  -g
> g++ -c -o write_gray_16.o write_gray_16.cpp -Wall -I.. -I/usr/local/include -I/home/shreyas/anaconda2/include/libpng16  -g
> g++ -o write_gray_16 write_gray_16.o -L/usr/local/lib -L/home/shreyas/anaconda2/lib -lpng16  -g
> g++ -c -o read_write_param.o read_write_param.cpp -Wall -I.. -I/usr/local/include -I/home/shreyas/anaconda2/include/libpng16  -g
> g++ -o read_write_param read_write_param.o -L/usr/local/lib -L/home/shreyas/anaconda2/lib -lpng16  -g
> g++ -c -o dump.o dump.cpp -Wall -I.. -I/usr/local/include -I/home/shreyas/anaconda2/include/libpng16  -g
> g++ -o dump dump.o -L/usr/local/lib -L/home/shreyas/anaconda2/lib -lpng16  -g
> ./test.sh
> PNG++ FAILS TESTS (154 OF 1566 FAILED)
> review test.log for clues
> 
> make[1]: *** [test] Error 1
> make[1]: Leaving directory `/home/shreyas/png++-0.2.9/test'
> make: *** [test] Error 2

I'm hoping someone here knows how to fix this issue. I'm a bit lost. Any help is greatly appreciated.

FYI, this is what my test.log file looks like (154 errors)

> convert_color_space: expected 8-bit data but found 16-bit; recompile with PNG_READ_16_TO_8_SUPPORTED
> convert_color_space: expected 8-bit data but found 16-bit; recompile with PNG_READ_16_TO_8_SUPPORTED
> convert_color_space: expected 8-bit data but found 16-bit; recompile with PNG_READ_16_TO_8_SUPPORTED
> convert_color_space: expected 8-bit data but found 16-bit; recompile with PNG_READ_16_TO_8_SUPPORTED
> convert_color_space: expected 8-bit data but found 16-bit; recompile with PNG_READ_16_TO_8_SUPPORTED
> convert_color_space: expected 8-bit data but found 16-bit; recompile with PNG_READ_16_TO_8_SUPPORTED
> convert_color_space: expected 8-bit data but found 16-bit; recompile with PNG_READ_16_TO_8_SUPPORTED
> convert_color_space: expected 8-bit data but found 16-bit; recompile with PNG_READ_16_TO_8_SUPPORTED
> convert_color_space: expected 8-bit data but found 16-bit; recompile with PNG_READ_16_TO_8_SUPPORTED
> convert_color_space: expected 8-bit data but found 16-bit; recompile with PNG_READ_16_TO_8_SUPPORTED
> convert_color_space: expected 8-bit data but found 16-bit; recompile with PNG_READ_16_TO_8_SUPPORTED
> convert_color_space: expected 8-bit data but found 16-bit; recompile with PNG_READ_16_TO_8_SUPPORTED
> convert_color_space: expected 8-bit data but found 16-bit; recompile with PNG_READ_16_TO_8_SUPPORTED
> convert_color_space: expected 8-bit data but found 16-bit; recompile with PNG_READ_16_TO_8_SUPPORTED
> out/pngsuite/basi2c16.png.GRAY.16.out cmp/pngsuite/basi2c16.png.GRAY.16.out differ: byte 60, line 3
> out/pngsuite/basi2c16.png.GRAY.16.out cmp/pngsuite/basi2c16.png.GRAY.16.out differ: byte 60, line 3
> convert_color_space: expected 8-bit data but found 16-bit; recompile with PNG_READ_16_TO_8_SUPPORTED
> convert_color_space: expected 8-bit data but found 16-bit; recompile with PNG_READ_16_TO_8_SUPPORTED
> out/pngsuite/basi2c16.png.GA.16.out cmp/pngsuite/basi2c16.png.GA.16.out differ: byte 53, line 3
> out/pngsuite/basi2c16.png.GA.16.out cmp/pngsuite/basi2c16.png.GA.16.out differ: byte 53, line 3
> convert_color_space: expected 8-bit data but found 16-bit; recompile with PNG_READ_16_TO_8_SUPPORTED
> convert_color_space: expected 8-bit data but found 16-bit; recompile with PNG_READ_16_TO_8_SUPPORTED
> convert_color_space: expected 8-bit data but found 16-bit; recompile with PNG_READ_16_TO_8_SUPPORTED
> convert_color_space: expected 8-bit data but found 16-bit; recompile with PNG_READ_16_TO_8_SUPPORTED
> convert_color_space: expected 8-bit data but found 16-bit; recompile with PNG_READ_16_TO_8_SUPPORTED
> convert_color_space: expected 8-bit data but found 16-bit; recompile with PNG_READ_16_TO_8_SUPPORTED
> convert_color_space: expected 8-bit data but found 16-bit; recompile with PNG_READ_16_TO_8_SUPPORTED
> convert_color_space: expected 8-bit data but found 16-bit; recompile with PNG_READ_16_TO_8_SUPPORTED
> convert_color_space: expected 8-bit data but found 16-bit; recompile with PNG_READ_16_TO_8_SUPPORTED
> convert_color_space: expected 8-bit data but found 16-bit; recompile with PNG_READ_16_TO_8_SUPPORTED
> convert_color_space: expected 8-bit data but found 16-bit; recompile with PNG_READ_16_TO_8_SUPPORTED
> convert_color_space: expected 8-bit data but found 16-bit; recompile with PNG_READ_16_TO_8_SUPPORTED
> convert_color_space: expected 8-bit data but found 16-bit; recompile with PNG_READ_16_TO_8_SUPPORTED
> convert_color_space: expected 8-bit data but found 16-bit; recompile with PNG_READ_16_TO_8_SUPPORTED
> out/pngsuite/basi6a16.png.GRAY.16.out cmp/pngsuite/basi6a16.png.GRAY.16.out differ: byte 53, line 3
> out/pngsuite/basi6a16.png.GRAY.16.out cmp/pngsuite/basi6a16.png.GRAY.16.out differ: byte 53, line 3
> convert_color_space: expected 8-bit data but found 16-bit; recompile with PNG_READ_16_TO_8_SUPPORTED
> convert_color_space: expected 8-bit data but found 16-bit; recompile with PNG_READ_16_TO_8_SUPPORTED
> out/pngsuite/basi6a16.png.GA.16.out cmp/pngsuite/basi6a16.png.GA.16.out differ: byte 53, line 3
> out/pngsuite/basi6a16.png.GA.16.out cmp/pngsuite/basi6a16.png.GA.16.out differ: byte 53, line 3
> convert_color_space: expected 8-bit data but found 16-bit; recompile with PNG_READ_16_TO_8_SUPPORTED
> convert_color_space: expected 8-bit data but found 16-bit; recompile with PNG_READ_16_TO_8_SUPPORTED
> convert_color_space: expected 8-bit data but found 16-bit; recompile with PNG_READ_16_TO_8_SUPPORTED
> convert_color_space: expected 8-bit data but found 16-bit; recompile with PNG_READ_16_TO_8_SUPPORTED
> convert_color_space: expected 8-bit data but found 16-bit; recompile with PNG_READ_16_TO_8_SUPPORTED
> convert_color_space: expected 8-bit data but found 16-bit; recompile with PNG_READ_16_TO_8_SUPPORTED
> convert_color_space: expected 8-bit data but found 16-bit; recompile with PNG_READ_16_TO_8_SUPPORTED
> convert_color_space: expected 8-bit data but found 16-bit; recompile with PNG_READ_16_TO_8_SUPPORTED
> convert_color_space: expected 8-bit data but found 16-bit; recompile with PNG_READ_16_TO_8_SUPPORTED
> convert_color_space: expected 8-bit data but found 16-bit; recompile with PNG_READ_16_TO_8_SUPPORTED
> convert_color_space: expected 8-bit data but found 16-bit; recompile with PNG_READ_16_TO_8_SUPPORTED
> convert_color_space: expected 8-bit data but found 16-bit; recompile with PNG_READ_16_TO_8_SUPPORTED
> convert_color_space: expected 8-bit data but found 16-bit; recompile with PNG_READ_16_TO_8_SUPPORTED
> convert_color_space: expected 8-bit data but found 16-bit; recompile with PNG_READ_16_TO_8_SUPPORTED
> out/pngsuite/basn2c16.png.GRAY.16.out cmp/pngsuite/basn2c16.png.GRAY.16.out differ: byte 53, line 3
> out/pngsuite/basn2c16.png.GRAY.16.out cmp/pngsuite/basn2c16.png.GRAY.16.out differ: byte 53, line 3
> convert_color_space: expected 8-bit data but found 16-bit; recompile with PNG_READ_16_TO_8_SUPPORTED
> convert_color_space: expected 8-bit data but found 16-bit; recompile with PNG_READ_16_TO_8_SUPPORTED
> out/pngsuite/basn2c16.png.GA.16.out cmp/pngsuite/basn2c16.png.GA.16.out differ: byte 52, line 3
> out/pngsuite/basn2c16.png.GA.16.out cmp/pngsuite/basn2c16.png.GA.16.out differ: byte 52, line 3
> convert_color_space: expected 8-bit data but found 16-bit; recompile with PNG_READ_16_TO_8_SUPPORTED
> convert_color_space: expected 8-bit data but found 16-bit; recompile with PNG_READ_16_TO_8_SUPPORTED
> convert_color_space: expected 8-bit data but found 16-bit; recompile with PNG_READ_16_TO_8_SUPPORTED
> convert_color_space: expected 8-bit data but found 16-bit; recompile with PNG_READ_16_TO_8_SUPPORTED
> convert_color_space: expected 8-bit data but found 16-bit; recompile with PNG_READ_16_TO_8_SUPPORTED
> convert_color_space: expected 8-bit data but found 16-bit; recompile with PNG_READ_16_TO_8_SUPPORTED
> convert_color_space: expected 8-bit data but found 16-bit; recompile with PNG_READ_16_TO_8_SUPPORTED
> convert_color_space: expected 8-bit data but found 16-bit; recompile with PNG_READ_16_TO_8_SUPPORTED
> convert_color_space: expected 8-bit data but found 16-bit; recompile with PNG_READ_16_TO_8_SUPPORTED
> convert_color_space: expected 8-bit data but found 16-bit; recompile with PNG_READ_16_TO_8_SUPPORTED
> convert_color_space: expected 8-bit data but found 16-bit; recompile with PNG_READ_16_TO_8_SUPPORTED
> convert_color_space: expected 8-bit data but found 16-bit; recompile with PNG_READ_16_TO_8_SUPPORTED
> convert_color_space: expected 8-bit data but found 16-bit; recompile with PNG_READ_16_TO_8_SUPPORTED
> convert_color_space: expected 8-bit data but found 16-bit; recompile with PNG_READ_16_TO_8_SUPPORTED
> out/pngsuite/basn6a16.png.GRAY.16.out cmp/pngsuite/basn6a16.png.GRAY.16.out differ: byte 53, line 3
> out/pngsuite/basn6a16.png.GRAY.16.out cmp/pngsuite/basn6a16.png.GRAY.16.out differ: byte 53, line 3
> convert_color_space: expected 8-bit data but found 16-bit; recompile with PNG_READ_16_TO_8_SUPPORTED
> convert_color_space: expected 8-bit data but found 16-bit; recompile with PNG_READ_16_TO_8_SUPPORTED
> out/pngsuite/basn6a16.png.GA.16.out cmp/pngsuite/basn6a16.png.GA.16.out differ: byte 53, line 3
> out/pngsuite/basn6a16.png.GA.16.out cmp/pngsuite/basn6a16.png.GA.16.out differ: byte 53, line 3
> convert_color_space: expected 8-bit data but found 16-bit; recompile with PNG_READ_16_TO_8_SUPPORTED
> convert_color_space: expected 8-bit data but found 16-bit; recompile with PNG_READ_16_TO_8_SUPPORTED
> convert_color_space: expected 8-bit data but found 16-bit; recompile with PNG_READ_16_TO_8_SUPPORTED
> convert_color_space: expected 8-bit data but found 16-bit; recompile with PNG_READ_16_TO_8_SUPPORTED
> convert_color_space: expected 8-bit data but found 16-bit; recompile with PNG_READ_16_TO_8_SUPPORTED
> convert_color_space: expected 8-bit data but found 16-bit; recompile with PNG_READ_16_TO_8_SUPPORTED
> convert_color_space: expected 8-bit data but found 16-bit; recompile with PNG_READ_16_TO_8_SUPPORTED
> convert_color_space: expected 8-bit data but found 16-bit; recompile with PNG_READ_16_TO_8_SUPPORTED
> convert_color_space: expected 8-bit data but found 16-bit; recompile with PNG_READ_16_TO_8_SUPPORTED
> convert_color_space: expected 8-bit data but found 16-bit; recompile with PNG_READ_16_TO_8_SUPPORTED
> convert_color_space: expected 8-bit data but found 16-bit; recompile with PNG_READ_16_TO_8_SUPPORTED
> convert_color_space: expected 8-bit data but found 16-bit; recompile with PNG_READ_16_TO_8_SUPPORTED
> convert_color_space: expected 8-bit data but found 16-bit; recompile with PNG_READ_16_TO_8_SUPPORTED
> convert_color_space: expected 8-bit data but found 16-bit; recompile with PNG_READ_16_TO_8_SUPPORTED
> out/pngsuite/bgan6a16.png.GRAY.16.out cmp/pngsuite/bgan6a16.png.GRAY.16.out differ: byte 53, line 3
> out/pngsuite/bgan6a16.png.GRAY.16.out cmp/pngsuite/bgan6a16.png.GRAY.16.out differ: byte 53, line 3
> convert_color_space: expected 8-bit data but found 16-bit; recompile with PNG_READ_16_TO_8_SUPPORTED
> convert_color_space: expected 8-bit data but found 16-bit; recompile with PNG_READ_16_TO_8_SUPPORTED
> out/pngsuite/bgan6a16.png.GA.16.out cmp/pngsuite/bgan6a16.png.GA.16.out differ: byte 53, line 3
> out/pngsuite/bgan6a16.png.GA.16.out cmp/pngsuite/bgan6a16.png.GA.16.out differ: byte 53, line 3
> convert_color_space: expected 8-bit data but found 16-bit; recompile with PNG_READ_16_TO_8_SUPPORTED
> convert_color_space: expected 8-bit data but found 16-bit; recompile with PNG_READ_16_TO_8_SUPPORTED
> convert_color_space: expected 8-bit data but found 16-bit; recompile with PNG_READ_16_TO_8_SUPPORTED
> convert_color_space: expected 8-bit data but found 16-bit; recompile with PNG_READ_16_TO_8_SUPPORTED
> convert_color_space: expected 8-bit data but found 16-bit; recompile with PNG_READ_16_TO_8_SUPPORTED
> convert_color_space: expected 8-bit data but found 16-bit; recompile with PNG_READ_16_TO_8_SUPPORTED
> convert_color_space: expected 8-bit data but found 16-bit; recompile with PNG_READ_16_TO_8_SUPPORTED
> convert_color_space: expected 8-bit data but found 16-bit; recompile with PNG_READ_16_TO_8_SUPPORTED
> convert_color_space: expected 8-bit data but found 16-bit; recompile with PNG_READ_16_TO_8_SUPPORTED
> convert_color_space: expected 8-bit data but found 16-bit; recompile with PNG_READ_16_TO_8_SUPPORTED
> convert_color_space: expected 8-bit data but found 16-bit; recompile with PNG_READ_16_TO_8_SUPPORTED
> convert_color_space: expected 8-bit data but found 16-bit; recompile with PNG_READ_16_TO_8_SUPPORTED
> convert_color_space: expected 8-bit data but found 16-bit; recompile with PNG_READ_16_TO_8_SUPPORTED
> convert_color_space: expected 8-bit data but found 16-bit; recompile with PNG_READ_16_TO_8_SUPPORTED
> out/pngsuite/bgyn6a16.png.GRAY.16.out cmp/pngsuite/bgyn6a16.png.GRAY.16.out differ: byte 53, line 3
> out/pngsuite/bgyn6a16.png.GRAY.16.out cmp/pngsuite/bgyn6a16.png.GRAY.16.out differ: byte 53, line 3
> convert_color_space: expected 8-bit data but found 16-bit; recompile with PNG_READ_16_TO_8_SUPPORTED
> convert_color_space: expected 8-bit data but found 16-bit; recompile with PNG_READ_16_TO_8_SUPPORTED
> out/pngsuite/bgyn6a16.png.GA.16.out cmp/pngsuite/bgyn6a16.png.GA.16.out differ: byte 53, line 3
> out/pngsuite/bgyn6a16.png.GA.16.out cmp/pngsuite/bgyn6a16.png.GA.16.out differ: byte 53, line 3
> out/pngsuite/s09i3p02.png.RGB.8.out cmp/pngsuite/s09i3p02.png.RGB.8.out differ: byte 58, line 3
> out/pngsuite/s09i3p02.png.RGB.8.out cmp/pngsuite/s09i3p02.png.RGB.8.out differ: byte 58, line 3
> convert_color_space: expected 8-bit data but found 16-bit; recompile with PNG_READ_16_TO_8_SUPPORTED
> convert_color_space: expected 8-bit data but found 16-bit; recompile with PNG_READ_16_TO_8_SUPPORTED
> convert_color_space: expected 8-bit data but found 16-bit; recompile with PNG_READ_16_TO_8_SUPPORTED
> convert_color_space: expected 8-bit data but found 16-bit; recompile with PNG_READ_16_TO_8_SUPPORTED
> convert_color_space: expected 8-bit data but found 16-bit; recompile with PNG_READ_16_TO_8_SUPPORTED
> convert_color_space: expected 8-bit data but found 16-bit; recompile with PNG_READ_16_TO_8_SUPPORTED
> out/pngsuite/tbbn2c16.png.GRAY.16.out cmp/pngsuite/tbbn2c16.png.GRAY.16.out differ: byte 53, line 3
> out/pngsuite/tbbn2c16.png.GRAY.16.out cmp/pngsuite/tbbn2c16.png.GRAY.16.out differ: byte 53, line 3
> convert_color_space: expected 8-bit data but found 16-bit; recompile with PNG_READ_16_TO_8_SUPPORTED
> convert_color_space: expected 8-bit data but found 16-bit; recompile with PNG_READ_16_TO_8_SUPPORTED
> out/pngsuite/tbbn2c16.png.GA.16.out cmp/pngsuite/tbbn2c16.png.GA.16.out differ: byte 52, line 3
> out/pngsuite/tbbn2c16.png.GA.16.out cmp/pngsuite/tbbn2c16.png.GA.16.out differ: byte 52, line 3
> convert_color_space: expected 8-bit data but found 16-bit; recompile with PNG_READ_16_TO_8_SUPPORTED
> convert_color_space: expected 8-bit data but found 16-bit; recompile with PNG_READ_16_TO_8_SUPPORTED
> convert_color_space: expected 8-bit data but found 16-bit; recompile with PNG_READ_16_TO_8_SUPPORTED
> convert_color_space: expected 8-bit data but found 16-bit; recompile with PNG_READ_16_TO_8_SUPPORTED
> convert_color_space: expected 8-bit data but found 16-bit; recompile with PNG_READ_16_TO_8_SUPPORTED
> convert_color_space: expected 8-bit data but found 16-bit; recompile with PNG_READ_16_TO_8_SUPPORTED
> out/pngsuite/tbgn2c16.png.GRAY.16.out cmp/pngsuite/tbgn2c16.png.GRAY.16.out differ: byte 53, line 3
> out/pngsuite/tbgn2c16.png.GRAY.16.out cmp/pngsuite/tbgn2c16.png.GRAY.16.out differ: byte 53, line 3
> convert_color_space: expected 8-bit data but found 16-bit; recompile with PNG_READ_16_TO_8_SUPPORTED
> convert_color_space: expected 8-bit data but found 16-bit; recompile with PNG_READ_16_TO_8_SUPPORTED
> out/pngsuite/tbgn2c16.png.GA.16.out cmp/pngsuite/tbgn2c16.png.GA.16.out differ: byte 52, line 3
> out/pngsuite/tbgn2c16.png.GA.16.out cmp/pngsuite/tbgn2c16.png.GA.16.out differ: byte 52, line 3
> convert_color_space: expected 8-bit data but found 16-bit; recompile with PNG_READ_16_TO_8_SUPPORTED
> convert_color_space: expected 8-bit data but found 16-bit; recompile with PNG_READ_16_TO_8_SUPPORTED
> convert_color_space: expected 8-bit data but found 16-bit; recompile with PNG_READ_16_TO_8_SUPPORTED
> convert_color_space: expected 8-bit data but found 16-bit; recompile with PNG_READ_16_TO_8_SUPPORTED
> convert_color_space: expected 8-bit data but found 16-bit; recompile with PNG_READ_16_TO_8_SUPPORTED
> convert_color_space: expected 8-bit data but found 16-bit; recompile with PNG_READ_16_TO_8_SUPPORTED
> convert_color_space: expected 8-bit data but found 16-bit; recompile with PNG_READ_16_TO_8_SUPPORTED
> convert_color_space: expected 8-bit data but found 16-bit; recompile with PNG_READ_16_TO_8_SUPPORTED

Thank you very much in advance!

Regards,
Shreyas

**Comment by ShreyasSkandan** [comment]
Figured this one out!

Apparently libpng1.6 doesn't work well with Png++ version 0.2.9. I downgraded my libpng to version 1.2.50 and switched to the png++ 0.2.7 version and it works now.

**Comment by shengwenbo125** [comment]
Hi，how to downgraded libpng to version 1.2.50 ？

**Comment by hm510** [comment]
> Hi，how to downgraded libpng to version 1.2.50 ？

https://github.com/jzbontar/mc-cnn/issues/17#issuecomment-377492959

**Comment by hm510** [comment]
> Hi，how to downgraded libpng to version 1.2.50 ？

https://sourceforge.net/projects/libpng/files/
