### ISSUE TITLE
Problem about the results compared with Middlebury displayed results

### ISSUE THREAD

**Issue by shuluoshu** [jzbontar/mc-cnn#20]
@jzbontar  Hi, 
Thanks for your code, and after I ran the slow network to predict the trainingH datasets, I got much worser results than the results displayed on the Middlebury website, I wonder where I did something wrong, can you help me out ?
The command is as follows:
`./main.lua mb slow -a predict -net_fname net/net_mb_slow_-a_train_all.t7 -left im0.png -right im1.png -disp_max 190 
`
And one of the results can be compared as follows: The error rate(nocc) for Vintage by running the code is 34% while the result of Vintage image on Middlebury (MC-CNN-acrt ) is 24.8%.
![mc-cnn1](https://cloud.githubusercontent.com/assets/17999845/23258438/3b380380-fa03-11e6-99a7-a4776a749bfc.png)

Do I miss something important? Thanks  a  lot !

**Comment by jzbontar** [comment]
I think you didn't set the `-disp_max` parameter correctly. I believe it should be 380 (=760 / 2) for the Vintage stereo pair.

**Comment by shuluoshu** [comment]
Thanks a lot, sorry for that~

**Comment by wujunjie15** [comment]
@shuluoshu Hello, i set disp_max to 380. Unlike the official result, the error is still very large. Can you solve this problem? if you address the problem, please tell me some detail.
