### ISSUE TITLE
when i run the code on MiddleBury data,it occur an error, but the code is OK on kitti data

### ISSUE THREAD

**Issue by ZhaozhengPlus** [jzbontar/mc-cnn#26]
![image](https://cloud.githubusercontent.com/assets/18107059/25063792/0fd57962-2220-11e7-82c5-2f2f55ab3089.png)

**Comment by ZhaozhengPlus** [comment]
i don't know why

**Comment by ZhaozhengPlus** [comment]
i have two GPU on my computer, one is 12G titan X, the other one is 3G  GTX 780

**Comment by fengyiliu11** [comment]
I got the same error. Could you tell me if you have solved this problem?
