### ISSUE TITLE
how to running it on the window 7?

### ISSUE THREAD

**Issue by fangxu622** [jzbontar/mc-cnn#7]
can't ?

**Comment by jzbontar** [comment]
Do you mean Windows 7 the operating system or windows as in the receptive field size (7x7 instead of 9x9 or 11x11 as in the paper)?

**Comment by fangxu622** [comment]
Sorry, I mean that is Windows 7 OS...

**Comment by fangxu622** [comment]
now, it just ok ,Maybe I should install Virtual Machine on Windows 7 OS...thanks

**Comment by jzbontar** [comment]
I have not tried compiling on Windows 7 myself, but I think it might work. Did you get Torch 7 running on Windows (https://github.com/torch/torch7/wiki/Windows)?
