### ISSUE TITLE
Stereo_predict function issue

### ISSUE THREAD

**Issue by xiao1228** [jzbontar/mc-cnn#8]
Hi I run into an issue with the stereo_predict function which is from 
local outlier = torch.CudaTensor():resizeAs(disp[2]):zero()
when I use the kitti2015 dataset.

The output is this

> bad argument #1 to 'resizeAs' (torch.CudaTensor expected, got torch.CudaLongTensor)

Does anyone know what is the problem? Thank you in advance!

**Comment by jzbontar** [comment]
Hi, I can't seem to reproduce the bug. What was the command that you ran?

**Comment by xiao1228** [comment]
Hi @jzbontar I clone the code again and run again, the problem disappeared. Thank you
